### ISSUE TITLE
script doesn't work on g4 instance

### ISSUE THREAD

**Issue by Stealer0** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#13] opened 2020-01-17 22:53 UTC
There's SSL/TLS exception with github and no ParsecAuth.exe on the desktop

also GPU Updater doesn't work

```
This GPU (NVIDIA Tesla T4) requires a GRID driver downloaded from the AWS Support Site
Method invocation failed because [System.Object[]] does not contain a method named 'split'.
At C:\Users\Administrator\AppData\Roaming\ParsecLoader\GPU Updater Tool.ps1:85 char:1
+ ($AWSG4SupportPage.links.outerhtml -like "*vgaming-windows*").split(' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

We detected your system does not have a valid NVIDIA Driver installed
Installing NVIDIA Drivers may require 2 reboots in order to install correctly.
This means you may lose some play time for completing this driver upgrade.
Type Y to continue, or N to exit.
(Y/N): y
Method invocation failed because [System.Object[]] does not contain a method named 'split'.
At C:\Users\Administrator\AppData\Roaming\ParsecLoader\GPU Updater Tool.ps1:85 char:1
+ ($AWSG4SupportPage.links.outerhtml -like "*vgaming-windows*").split(' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Your PC already has the latest NVIDIA GPU Driver () available from nvidia.com.
Press any key to exit...:
```

Auto Recover GPU script also gives an exception

**Comment by piersg** [comment] 2020-01-26 01:54
For the record, I got the same on a g4dn.xlarge instance 
(all three things: 
- the TLS errors
- the "no split method" error
- no ParsecAuth.exe
)

What DOES seem to work pretty well is running the script on the pre-configured NVidia gaming Win 2016 AMI. That takes about 15 mins to set itself up the first time, but after that I ran these setup scripts, got the above errors, but you can sign in the Parsec over VNC and clients can connect and it  runs *pretty good* (on a sample of one 2013-era game)

**Comment by danielxvu** [comment] 2020-01-27 18:46
Also experiencing these issues on a g4dn.xlarge instance.

**Comment by jamesstringerparsec** [comment] 2020-01-27 23:07
The g4dn issue is caused by AWS now hiding their drivers in a private S3 bucket, which means there is no way for me to find out the new driver without needing you to provide an AWS access and secret key.  So I will need to refactor that part of the script to ask for those details.  

As far as ParsecAuth goes, yea that's missing.  It's waiting for a code review.  Basically what you need to do for now is not use RDP and instead use RDP to log into Parsec.

**Comment by Stealer0** [comment] 2020-01-28 00:00
>AWS now hiding their drivers in a private S3 bucket
But it was working they day before you made new update to the code?

**Comment by CloudDesktopComputing** [comment] 2020-01-30 13:36
I have followed the AWS instructions on installing the vGaming Driver & licensing it. Although Parsec detects the machine and can connect, the display resolution is not automatically set correctly, and there's no input being passed to the machine [IE, seemingly no keyboard or mouse instructions.] Any advice? Had no problems in the past like this.

**Comment by jamesstringerparsec** [comment] 2020-01-30 21:22
Hi guys, can you please try the executable below, this WONT fix the gpu driver issue but hopefully will let you see Parsec via RDP.  Let me know if it helps.

https://github.com/jamesstringerparsec/Parsec-Service-Manager

**Comment by jamesstringerparsec** [comment] 2020-02-04 14:07
This issue is solved

1. Copy all text from https://raw.githubusercontent.com/jamesstringerparsec/Parsec-Cloud-Preparation-Tool/master/PostInstall/PostInstall.ps1
2. Open  %appdata%\ParsecLoader\GPU Updater Tool.ps1 in Notepad, replace all text in the document with the text you copied from Step 1.
3. Save the file (**do not** Save As)
4.  Run GPU updater tool on the desktop

**Closed by jamesstringerparsec** 2020-02-04 14:07 UTC
